name: course-langchain-dev
services:
  CourseLangGraph:
    build:
      args:
        PROJECT_PATH: /course-langchain
      target: dev
      context: .
      dockerfile: Dockerfile
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - MODEL=${MODEL}
    volumes:
      - .:/course-langchain
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    command: ["sleep", "infinity"]
