name: courselanggraph-dev
services:
  courselanggraph:
    build:
      args:
        PROJECT_PATH: /course-langchain
      target: dev
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/course-langchain
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    command: ["sleep", "infinity"]
