services:
  courselanggraph:
    build:
      args:
        PROJECT_PATH: /course-langchain
      context: .
      dockerfile: Dockerfile
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - MODEL=${MODEL}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}
      - LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}
      - LANGFUSE_BASE_URL=${LANGFUSE_BASE_URL}
      - USE_GOOGLE_AI=${USE_GOOGLE_AI}
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    command: ["bash", "-c", "python app.py"]
